Repository cmsc388T-winter22/Team3, pull requests merged in 2022-01, with the labels that each got.

#67 Sabotage michaelko
  Projects/P1/src/Ghost.java
  Projects/P1/src/Map.java
  Projects/P1/src/PacMan.java
  Projects/P1/tests/TestMapAttack.java
Labels: enhancement

#65 sabotage-rnesbitt Complete
  Projects/P1/src/Ghost.java
  Projects/P1/src/Map.java
  Projects/P1/src/PacMan.java
  Projects/P1/tests/TestAttack.java
  Projects/P1/tests/TestConsume.java
  Projects/P1/tests/TestMapEatCookie.java
Labels: enhancement

#64 Sabotage scduffy
  Projects/P1/src/Ghost.java
  Projects/P1/src/Map.java
  Projects/P1/src/PacMan.java
  Projects/P1/tests/TestMapGetLoc.java
Labels: enhancement

#76 Actions benjamin shasho
  .github/workflows/main.yml
  Projects/P1/tests/TestGhostMove.java
  Projects/P1/tests/TestMapGetLoc.java
  Projects/P1/tests/TestPacManMove.java
Labels: documentation

#77 Actions scduffy
  .github/workflows/main.yml
  Projects/P1/tests/TestGhostValidMoves.java
  Projects/P1/tests/TestMapMove.java
  Projects/P1/tests/TestPacManValidMoves.java
Labels: documentation

#79 Fixed tests, should work now
  Projects/P1/tests/TestConsume.java
  Projects/P1/tests/TestMapEatCookie.java
Labels: enhancement

#80 test cases fixed
  Projects/P1/tests/TestGhostValidMoves.java
  Projects/P1/tests/TestMapMove.java
  Projects/P1/tests/TestPacManValidMoves.java
Labels: bug

#81 Ftr actions
  .github/workflows/main.yml
  Projects/P1/src/Ghost.java
  Projects/P1/src/Map.java
  Projects/P1/src/NoFrame.java
  Projects/P1/tests/TestAttack.java
  Projects/P1/tests/TestConsume.java
  Projects/P1/tests/TestGhostInRange.java
  Projects/P1/tests/TestGhostMove.java
  Projects/P1/tests/TestGhostValidMoves.java
  Projects/P1/tests/TestMapAttack.java
  Projects/P1/tests/TestMapEatCookie.java
  Projects/P1/tests/TestMapGetLoc.java
  Projects/P1/tests/TestMapMove.java
  Projects/P1/tests/TestPacManInRange.java
  Projects/P1/tests/TestPacManMove.java
  Projects/P1/tests/TestPacManValidMoves.java
Labels: enhancement

#82 Ftr sabotage
  Projects/P1/src/Ghost.java
  Projects/P1/src/Map.java
  Projects/P1/src/PacMan.java
  Projects/P1/tests/TestMapEatCookie.java
  Projects/P1/tests/TestMapGetLoc.java
Labels: enhancement
